hasker/apps/userprofile/urls.py
from django.urls import path

from . import views

app_name = "profile"
urlpatterns = [
    path("profile/", views.ProfileUpdateView.as_view(), name="profile"),
    path("create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("complete/", views.ProfileCompleteView.as_view(), name="profile_created"),
]

hasker/hasker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("userprofile.urls")),
    path("", include("qa.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

if hasattr(settings, 'SERVE_STATIC') and settings.SERVE_STATIC:
    # TODO: use whitenoise
    from django.views.static import serve
    from django.urls import re_path
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

if hasattr(settings, 'SERVE_MEDIA') and settings.SERVE_MEDIA:
    from django.views.static import serve
    from django.urls import re_path
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

hasker/templates/base.html
<!doctype html>
{% load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <title>{% block head-title%}{% endblock %}</title>
  <meta name="description" content="{% block head-description %}{%endblock%}">
  <meta name="author" content="(:">
  {%block core-css%}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  {%endblock%}
  {% block extra-css %}{%endblock%}
</head>

<body>
  {%block header %}
  <header id='header' class='container'>
    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
      <a href="/" class="navbar-brand text-dark">HASKER</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item {% if location == 'home' %}active{%endif%}">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {% if location == 'account' %}active{%endif%}">
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'profile:profile' %}">{{ request.user.username }}</a>
            {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
  </header>
  {% endblock %}
  <div class="container">
    {% block container %}{%endblock%}
    <div class="row">
      {% block title %}{%endblock%}
    </div>

    {% block content %}{%endblock%}
  </div>
  {% block core-js %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="{% static 'js/index.js' %}"></script>
  {%endblock%}
  {% block extra-js %}{%endblock%}
</body>

</html>